# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/gimp-print
pkglibdir = $(libdir)/gimp-print
pkgincludedir = $(includedir)/gimp-print

top_builddir = ../..

ACLOCAL = aclocal -I src/main
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i686-suse-linux
host_triplet = i686-suse-linux
ALL_LINGUAS = en_GB sv
AS = @AS@
AWK = gawk
BISON_PROG = /usr/bin/bison
BUILD_INCLUDED_LIBINTL = no
CATALOGS =  en_GB.gmo sv.gmo
CATOBJEXT = .gmo
CC = gcc
CONVERT = /usr/bin/convert
CUPS_BACKEND_BIN = 
CUPS_BIN = 
CUPS_CONF = 
CUPS_FILTER_BIN = 
CUPS_INSTALL = 
CUPS_LIBS =  -lm
CUPS_MAN = 
CUPS_NOINST_BIN = 
CUPS_PKG = 
DATADIRNAME = share
DB2HTML = /usr/bin/db2html
DB2PDF = /usr/bin/db2pdf
DB2PS = /usr/bin/db2ps
DLLTOOL = @DLLTOOL@
DVIPS = /usr/bin/dvips
ESCPUTIL_BIN = $(ESCPUTIL_BIN)
ESCPUTIL_MAN = $(ESCPUTIL_MAN)
FOOMATIC_INSTALL = 
FOOMATIC_KITLOAD = 
FOOMATIC_NOINST_BIN = 
GENCAT = gencat
GIMPPRINT_BINARY_AGE = 0
GIMPPRINT_CFLAGS = 
GIMPPRINT_CONFIG = 
GIMPPRINT_CURRENT_INTERFACE = 1
GIMPPRINT_DEPLIBS =  -lm
GIMPPRINT_INTERFACE_AGE = 0
GIMPPRINT_LIBS = -lgimpprint
GIMPPRINT_MAJOR_VERSION = 4
GIMPPRINT_MICRO_VERSION = 99
GIMPPRINT_MINOR_VERSION = 1
GIMPPRINT_VERSION = 4.1.99-b3
GIMPTOOL = /usr/bin/gimptool
GIMP_BIN = $(GIMP_BIN)
GIMP_CFLAGS = -I/usr/include/gtk-1.2 -I/usr/include/glib-1.2 -I/usr/lib/glib/include -I/usr/X11R6/include
GIMP_CFLAGS_NOUI = -I/usr/lib/glib/include -I/usr/X11R6/include
GIMP_DATA_DIR = /usr/share/gimp/1.2
GIMP_LIBS = -L/usr/lib -lgimpui -lgimp -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXi -lXext -lX11 -lm
GIMP_LIBS_NOUI = -L/usr/lib -lgimp -lglib
GIMP_PLUGIN_DIR = /usr/lib/gimp/1.2
GIMP_PRINT_H = gimp-print.h
GLIBC21 = yes
GLIB_CFLAGS = 
GLIB_CONFIG = 
GLIB_LIBS = 
GMOFILES =  en_GB.gmo sv.gmo
GMSGFMT = /usr/local/bin/msgfmt
GNUCFLAGS = -Wall -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wwrite-strings -pedantic
GTK_CFLAGS = 
GTK_CONFIG = 
GTK_LIBS = 
GZIP = /usr/bin/gzip
INCLUDES =  -I$(top_srcdir)/include -I$(top_builddir)/include -I$(top_srcdir)/intl
INSTOBJEXT = .mo
INTLBISON = bison
INTLLIBS = 
INTLOBJS = 
INTL_LIBTOOL_SUFFIX_PREFIX = 
JADE = /usr/bin/jade
LEX = flex
LIBGIMPPRINT_LIBS = $(top_builddir)/src/main/libgimpprint.la  -lm
LIBICONV = 
LIBREADLINE_DEPS = -lreadline
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = scripts/ltconfig scripts/ltmain.sh
LN_S = ln -s
LTALLOCA = 
LTLIBOBJS =  xgetcwd.lo xmalloc.lo
LT_AGE = 0
LT_CURRENT = 1
LT_RELEASE = 4.1
LT_REVISION = 0
MAINT = 
MAINTAINER_CFLAGS = 
MAIN_BIN = $(MAIN_BIN)
MAIN_DAT = $(MAIN_DAT)
MAIN_MAN = $(MAIN_MAN)
MAIN_SCR = $(MAIN_SCR)
MAKEINFO = makeinfo
MKINSTALLDIRS = scripts/mkinstalldirs
MSGFMT = /usr/local/bin/msgfmt
OBJDUMP = @OBJDUMP@
PACKAGE = gimp-print
PERL = /usr/bin/perl
PLUG_IN_PATH = admin-bin
POFILES =  en_GB.po sv.po
POSUB = po
PRINT_VASPRINTF = 
PS2PDF = /usr/local/bin/ps2pdf
RANLIB = ranlib
RELEASE_DATE = 03 Oct 2001
SAMPLE_IMAGES = $(SAMPLE_IMAGES)
TESTPATTERN_BIN = 
TEST_BIN = $(TEST_BIN)
TEXI2HTML = /usr/bin/texi2html
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 4.1.99-b3
YACC = bison -y
YACC_PROG = /usr/bin/yacc
cups_bindir = /usr/bin
cups_datadir = /usr/share
cups_exec_prefix = /usr
cups_libdir = /usr/lib
cups_prefix = /usr
cups_sysconfdir = /etc
gimpprint_cflags = 
gimpprint_libs = -lgimpprint  -lm

AUTOMAKE_OPTIONS = 1.4 gnu

MAINT_CHARSET = latin1

MANUAL = users_guide
HTML_DIR = $(MANUAL)

OUTPUTS =   $(MANUAL).pdf  $(MANUAL).ps  html


DISTDIRS = figures

CATALOG_FILES = /etc/sgml/catalog

PNG_IMAGES = $(wildcard figures/*.png)

EPS_IMAGES = $(addsuffix .eps,$(basename $(PNG_IMAGES)))
PDF_IMAGES = $(addsuffix .pdf,$(basename $(PNG_IMAGES)))

MAINTAINERCLEANFILES = Makefile.in

EXTRA_DIST = README $(MANUAL).sgml
mkinstalldirs = $(SHELL) $(top_srcdir)/scripts/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
DIST_COMMON =  README Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in:  Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu doc/users_guide/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = doc/users_guide

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu doc/users_guide/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am clean-local

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean




dist-hook:
	for dir in $(DISTDIRS) ; do \
	  if test -d $(srcdir)/$$dir ; then \
	    mkdir $(distdir)/$$dir; \
	    for dirfile in $(srcdir)/$$dir/*; do \
	      if test -f $$dirfile ; then \
	        cp -p $$dirfile $(distdir)/$$dir; \
	      fi \
	    done \
	  fi \
	done

#
# This generates nicer PDF than the uncommented method.
# However, the pictures are missing.  I don't know
# what format to supply to DocBook get the correct output.
#
#$(MANUAL).pdf:  $(MANUAL).sgml $(PDF_IMAGES)
#	export SGML_CATALOG_FILES=$(CATALOG_FILES); \
#	$(DB2PDF) $(MANUAL).sgml

pdf: $(MANUAL).pdf

$(MANUAL).pdf: $(MANUAL).ps
	$(PS2PDF) $(MANUAL).ps $(MANUAL).pdf

%.pdf:
	if test ! -d figures ; then \
	  mkdir figures ; \
	fi
	$(CONVERT) $(srcdir)/$(basename $@).png EPDF:$@

ps: $(MANUAL).ps

ps.gz: $(MANUAL).ps.gz

$(MANUAL).ps:  $(MANUAL).sgml $(EPS_IMAGES)
	export SGML_CATALOG_FILES=$(CATALOG_FILES); \
	$(DB2PS) $(MANUAL).sgml

%.eps:
	if test ! -d figures ; then \
	  mkdir figures ; \
	fi
	$(CONVERT) $(srcdir)/$(basename $@).png EPS2:$@

$(MANUAL).ps.gz: $(MANUAL).ps
	rm -f $(MANUAL).ps.gz
	$(GZIP) -9 $(MANUAL).ps

html: html-stamp
html-stamp: $(MANUAL).sgml $(PNG_IMAGES)
	export SGML_CATALOG_FILES=$(CATALOG_FILES) ; \
	$(DB2HTML) $(MANUAL).sgml ; \
	if [ ! -L $(MANUAL)/figures ] ; then \
	  cd $(HTML_DIR) ; \
	  $(LN_S) ../figures figures ; \
	fi ; \
	cd ..; \
	mv $(MANUAL) html
	touch html-stamp

tmp-all-local: html
	if test -d $(srcdir)/$(HTML_DIR) ; then \
	  if test "$(srcdir)" = "." ; then \
	    echo "all-local: Not removing manual-html" ; \
	  else \
	    rm -rf $(HTML_DIR) ; \
	    $(LN_S) $(srcdir)/$(HTML_DIR) $(HTML_DIR) ; \
	  fi \
	  else \
	    echo "all-local: $(srcdir)/$(HTML_DIR) not found" ; \
	fi

clean-local:
	rm -f $(OUTPUTS)
	rm -f *.tex *.log *.aux *.dvi *.tgz
	rm -fr $(MANUAL)
	rm -fr $(MANUAL).junk
	rm -f $(MANUAL).out
	rm -fr db2html.*
	rm -rf figures/*.eps figures/*.pdf
	rm -fr html-stamp

#
# This is my (so far failed) attempt to create an index for this documentation.
#

index.sgml:
	$(PERL) /usr/share/sgml/docbook/docbook-dsssl-stylesheets-1.64/bin/collateindex.pl -N -o index.sgml

	$(JADE)	-V html-index \
		-t sgml \
		-c /usr/share/sgml/CATALOG.jade_dsl \
		-c /usr/share/sgml/CATALOG.docbook-dsssl-stylesheets \
		-c /usr/share/sgml/CATALOG.gnome \
		-c /usr/share/sgml/CATALOG.docbook_4 \
		-c /usr/share/sgml/CATALOG.docbook_3  \
		-D /usr/share/sgml/docbook/docbook-dsssl-stylesheets-1.64 \
		-d /usr/share/sgml/docbook-toys/suse-both.dsl \
		-o index.sgml \
		gimp-print-users-guide-4.1.99-b3.sgml

#
# END failed attempt at index creation.  
#

help:
	@echo "  "
	@echo "Supported targets in this Makefile:"
	@echo "    all     - creates PS, PDF, and HTML documentation files"
	@echo "    clean   - deletes machine generated files"
	@echo "    help    - prints this help text"
	@echo "  "

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
