#!/bin/bash -e

#
# Determine the current version of Gutenprint, based on the contents of the
# 'gutenprint.pc' file that is a part of a build. Because of that, it must be
# run after a build.
#
# The output is the combination of version and subversion.
#

pkg_config_file="build/10.6/install/usr/lib/pkgconfig/gutenprint.pc"
subversion_file="subversion"

if [ ! -e $pkg_config_file ]; then
  echo "No config file found at $pkg_config_file"
  exit 1
fi

version=$(grep 'Version:' $pkg_config_file | awk -F': ' '{print $2}')

if [ -z $version ]; then
  echo "Failed to determine version number from $pkg_config_file"
  exit 1
fi

if [ -e "$subversion_file" ]; then
  subversion=$(cat "$subversion_file")
fi

echo "$version$subversion"