#!/bin/sh

rm -rf ppd ppd-stamp

make ppd

ppd_count=`find ppd \( -name '*.ppd.gz' -o -name '*.ppd' \) -print | wc -l`

failures="`find ppd -name '*.ppd*' -print | xargs cupstestppd |grep 'FAIL$' | awk -F: '{print $1}'`"

if [ -z "$failures" ] ; then
    echo "All $ppd_count PPD files pass"
    exit 0
fi

echo $failures | xargs cupstestppd

fail_count=`echo "$failures" | wc -l`
echo "$fail_count/$ppd_count fail"
exit 1
