#!/bin/bash -e

#set -x  # uncomment for debugging

pkg_dir="$1"

alternate_bins_dir="$pkg_dir/Contents/usr/share/gutenprint/alternate-binaries"

# install everything for 10.5+
cp -pR build/10.5/install/* "$pkg_dir/Contents"

# then build alternate binaries directory, which will be installed
# by the postinstall/postupgrade scripts
mkdir -p "$alternate_bins_dir"
for i in usr/sbin/cups-genppdupdate \
         ; do
  cp -p build/10.5-cups-ppds/install/$i "$alternate_bins_dir"
done

# install documentation from 10.6
for i in usr/share/gutenprint/doc/gutenprint.pdf \
         usr/share/gutenprint/doc/reference-html \
         ; do
   cp -pR build/10.6/install/$i "$pkg_dir/Contents/$(dirname $i)"
done

# remove the execute bit, per policy of /usr/share -- it will be reset
# by the postinstall/postupgrade script
chmod -x "$alternate_bins_dir"/*