#! /bin/sh
# mkinstalldirs --- make directory hierarchy
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1993-05-16
# Public domain

# $Id$

errstatus=0


# A really nasty hack to allow 'make gdist' to work properly while
# not confusing make install
# I take full responsibility for this botch --rlk

if [ -n "$1" -a -z "`echo $1 | grep '^/'`" ] ; then
   base=`dirname $1`/
   extras=`find Ghost/stp-interfaces -type d -print | sed "s,^,$base,"`
fi

for file in "$@" $extras
do
   set fnord `echo ":$file" | sed -ne 's/^:\//#/;s/^://;s/\// /g;s/^#/\//;p'`
   shift

   pathcomp=
   for d
   do
     pathcomp="$pathcomp$d"
     case "$pathcomp" in
       -* ) pathcomp=./$pathcomp ;;
     esac

     if test ! -d "$pathcomp"; then
        echo "mkdir $pathcomp"

        mkdir "$pathcomp" || lasterr=$?

        if test ! -d "$pathcomp"; then
  	  errstatus=$lasterr
        fi
     fi

     pathcomp="$pathcomp/"
   done
done

exit $errstatus

# mkinstalldirs ends here
