#!/bin/sh

modes='20,8 21,8 32,8 48,6 64,4 64,8 96,2 128,4 128,8 144,6 192,2'
passes='1,1,1 2,1,1 1,2,1 1,2,2 1,4,1 2,2,1 1,4,2 2,2,2'

jets='20 21 32 48 64 96 128 144 192'
separations='2 4 6 8'

for jet in $jets ; do
    for sep in $separations ; do
	for pass in $passes ; do
	    stuff=`echo "$jet,$sep,$pass" | awk -F, '{printf "%d %d %d %d %d\n", $1, $2, $3, $4, $5}'`
	    a=`echo $stuff | cut -f1 '-d '`
	    b=`echo $stuff | cut -f2 '-d '`
	    c=`echo $stuff | cut -f3 '-d '`
	    d=`echo $stuff | cut -f4 '-d '`
	    e=`echo $stuff | cut -f5 '-d '`
	    ./escp2-weavetest $stuff 10000 > /dev/null 2>&1
	    if [ $? -ne 0 ] ; then
		if [ -n "`echo $modes | grep $jet,$sep`" ] ; then
		    echo -n '*'
		elif [ $a -lt `expr $b \* $c \* $d \* $e` ] ; then
		    echo -n '!'
		else
		    echo -n ' '
		fi
		echo -n "$stuff  "
		./escp2-weavetest $stuff 10000 | tail -1
	    fi
	done
    done
done
