#!/bin/sh
# Run this to generate all the initial makefiles, etc.
# Shamelessly copied from Glade

DIE=0

if test -d m4local ; then
  :
else
  echo "Directory \`m4local' does not exist.  Creating it."
  if test -e m4local ; then
    echo "**Error**: A file \`m4local' exists and is not a directory."
    echo "Please remove it."
    DIE=1
  fi
  mkdir m4local
fi

if test -d m4 ; then
  rm -rf m4
elif -e m4 ; then
  echo "**Error**: A file \`m4local' exists and is not a directory."
  echo "Please remove it."
  exit 1
fi

mkdir m4
cat > m4/stp.m4 <<\EOF
# This file is part of Gutenprint.                     -*- Autoconf -*-
# Gutenprint Autoconf support.
# Copyright 2001-2002 Roger Leigh
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 02111-1307, USA.

# PLEASE DO NOT EDIT THIS FILE.
# Edit the here document in scripts/autogen.sh.

## Table of Contents:
## 1. Autoconf support


## ---------------- ##
## Autoconf support ##
## ---------------- ##


# STP_INIT
# --------
# Initialise Gutenprint autoconf macros.  Turn on error detection of
# STP_* macros
AC_DEFUN([STP_INIT],
[m4_pattern_forbid([STP_])])

AC_DEFUN([CONFIG_FILE_EXEC],
[AC_CONFIG_FILES([$1], [chmod +x $1])])

EOF
cat > m4/stp_cups.m4 <<\EOF
# This file is part of Gutenprint.                     -*- Autoconf -*-
# CUPS support.
# Copyright 2000-2002 Roger Leigh
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 02111-1307, USA.

# PLEASE DO NOT EDIT THIS FILE.
# Edit the here document in scripts/autogen.sh.


## ------------ ##
## CUPS support ##
## ------------ ##


# STP_CUPS_LIBS
# -------------
# Check for CUPS libraries.
AC_DEFUN([STP_CUPS_LIBS],
[dnl CUPS library checks
dnl check for libm, and also add to CUPS LIBS
AC_CHECK_LIB(m,pow,
  CUPS_LIBS="${CUPS_LIBS} -lm")
dnl CUPS library checks
if test x${BUILD_CUPS} = xyes ; then
  AC_CHECK_LIB(z,gzgets,
    HAVE_LIBZ=true, HAVE_LIBZ=false)
  if test x${HAVE_LIBZ} = xtrue ; then
    GENPPD_LIBS="-lz"
    AC_DEFINE(HAVE_LIBZ,, [Define if libz is present.])
  fi
  AC_PATH_PROG(CUPS_CONFIG, cups-config)
  if test "x$CUPS_CONFIG" != x; then
    dnl Use values from CUPS config...
    CUPS_LIBS="`$CUPS_CONFIG --ldflags` `$CUPS_CONFIG --image --libs`"
    CUPS_CFLAGS="`$CUPS_CONFIG --cflags`"
  else
    dnl Save current library list...
    SAVELIBS="$LIBS"
    LIBS="$LIBS ${CUPS_LIBS}"
    AC_CHECK_LIB(socket,socket,
      if test x${OSTYPE} != xirix ; then
      CUPS_LIBS="${CUPS_LIBS} -lsocket"
      LIBS="$LIBS -lsocket"
    fi)
    AC_CHECK_LIB(nsl,gethostbyaddr,
      if test x${OSTYPE} != xirix ; then
      CUPS_LIBS="${CUPS_LIBS} -lnsl"
      LIBS="$LIBS -lnsl"
    fi)

    dnl Some OS's need to link against crypto stuff too if CUPS is compiled
    dnl with crypto support... :(
    AC_CHECK_HEADER(openssl/ssl.h,
      dnl Some ELF systems can't resolve all the symbols in libcrypto
      dnl if libcrypto was linked against RSAREF, and fail to link the
      dnl test program correctly, even though a correct installation
      dnl of OpenSSL exists.  So we test the linking three times in
      dnl case the RSAREF libraries are needed.

      SSL="no"

      for libcrypto in \
	  "-lcrypto" \
	  "-lcrypto -lrsaref" \
	  "-lcrypto -lRSAglue -lrsaref"
      do
	  AC_CHECK_LIB(ssl,SSL_new,
	      [CUPS_LIBS="${CUPS_LIBS} -lssl $libcrypto"
	       SSL="yes"],,
	      $libcrypto)

	  if test x$SSL = xyes; then
	      break
	  fi
      done)

    dnl Require CUPS 1.1...
    AC_CHECK_LIB(cups,cupsPrintFiles,
      CUPS_LIBS="${CUPS_LIBS} -lcups",
      LIBS="$LIBS -lcups"
      AC_MSG_ERROR([Cannot find CUPS libraries (libcups)]))
    AC_CHECK_LIB(cupsimage,cupsRasterOpen,
      CUPS_LIBS="${CUPS_LIBS} -lcupsimage",
      AC_MSG_ERROR([Cannot find CUPS libraries (libcupsimage)]),
      -lcups)
    dnl Restore old library list...
    LIBS="$SAVELIBS"

    dnl Add CUPS include directory as needed...
    if test "x${cups_prefix}" != "x/usr" -a "x${cups_prefix}" != x; then
      CUPS_CFLAGS="-I${cups_prefix}/include"
    else
      CUPS_CFLAGS=""
    fi
  fi
fi
])

# STP_CUPS_PATH
# -------------
# Set CUPS install paths
AC_DEFUN([STP_CUPS_PATH],
[# CUPS path setup

# Fix "cups_prefix" variable if it hasn't been specified...
if test "x${cups_prefix}" = xNONE -o "x{$cups_prefix}" = x ; then
  if test "x${prefix}" = xNONE -o "x${prefix}" = x ; then
    cups_prefix="/usr"
  else
    cups_prefix="${prefix}"
  fi
fi

# Fix "cups_exec_prefix" variable if it hasn't been specified...
if test "x${cups_exec_prefix}" = xNONE  -o "x${cups_exec_prefix}" = x ; then
  if test x"${exec_prefix}" = xNONE -o "x${exec_prefix}" = x ; then
    cups_exec_prefix="${cups_prefix}"
  else
    cups_exec_prefix="${exec_prefix}"
  fi
fi

# Get explicit CUPS directories if possible
if test "x$CUPS_CONFIG" != x -a "x$NO_PKGCONFIG_PATHS" = x; then
  cups_conf_datadir="`$CUPS_CONFIG --datadir`"
  cups_conf_serverroot="`$CUPS_CONFIG --serverroot`"
  cups_conf_serverbin="`$CUPS_CONFIG --serverbin`"
else
  cups_conf_datadir="${cups_prefix}/share/cups"
  cups_conf_serverroot="${cups_prefix}/etc/cups"
  cups_conf_serverbin="${cups_exec_prefix}/lib/cups"
fi

# And the rest!
cups_bindir="${cups_exec_prefix}/bin"
cups_sbindir="${cups_exec_prefix}/sbin"

])

EOF

cat > m4/stp_option.m4 <<\EOF
# This file is part of Gutenprint.                     -*- Autoconf -*-
# Convenience macros.
# Copyright 2001-2002 Roger Leigh
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 02111-1307, USA.

# PLEASE DO NOT EDIT THIS FILE.
# Edit the here document in scripts/autogen.sh.

## Table of Contents:
## 1. Option handling
## 2. Conditionals


## ------------------ ##
## 1. Option handling ##
## ------------------ ##


## STP_ARG_WITH_DETAILED [(NAME, [NAME_OPTION], HELP, [HELP_OPTION],
## VARIABLE, DEFAULT, [OPTION_TRUE], [OPTION_FALSE])]
## -------------------------------------------------------------------
## Create a standardised configure option.
## NAME		Option name i.e. --with-foo or --enable-foo.
## NAME_OPTION	Optional input for use with NAME (informational).
## HELP		Help string to display.
## HELP_OPTION	Additional defaults information in addition to
##		DEFAULT.
## VARIABLE	Variable to set with command-line results.
## DEFAULT	Default value of VARIABLE.
## OPTION_TRUE	case statement body if an option is supplied.
##		This replaces the default actions.
## OPTION_FALSE Shell commands to run if no option is supplied.

AC_DEFUN([STP_ARG_WITH_DETAILED],
[# create custom command-line --with option
AC_MSG_CHECKING([whether to $3])
AC_ARG_WITH($1,
            [AC_HELP_STRING([--with-$1]m4_if([$2], , , [$2]),
              [$3 ]m4_if([$4], , , [$4 ])[@<:@]$6[@:>@])],
            [case "${withval}" in
            m4_if([$7], ,[
                yes) [$5]="yes" ; AC_MSG_RESULT(${[$5]}) ;;
                no) [$5]="no" ; AC_MSG_RESULT(${[$5]}) ;;
                *) AC_MSG_RESULT([unknown])
                   AC_MSG_ERROR([bad value ${withval} for --with-$1]) ;;
	    ], [$7])
	    esac],
            [if test -z "${[$5]}" ; then
               [$5]="$6"
             fi
             AC_MSG_RESULT(${[$5]}) ; m4_if([$8], , , [$8])])
if test -z "${[$5]}" ; then
  [$5]="$6"
fi
])


## STP_ARG_ENABLE_DETAILED [(NAME, [NAME_OPTION], HELP, [HELP_OPTION],
## VARIABLE, DEFAULT, [OPTION_TRUE], [OPTION_FALSE])]
## -------------------------------------------------------------------
## Create a standardised configure option.
## Identical to ATP_ARG_WITH_DETAILED.
AC_DEFUN([STP_ARG_ENABLE_DETAILED],
[# create custom command-line --enable option
AC_MSG_CHECKING([whether to $3])
AC_ARG_ENABLE($1,
            [AC_HELP_STRING([--enable-$1]m4_if([$2], , , [$2]),
              [$3 ]m4_if([$4], , , [$4 ])[@<:@]$6[@:>@])],
            [case "${enableval}" in
            m4_if([$7], ,[
                yes) [$5]="yes" ; AC_MSG_RESULT(${[$5]}) ;;
                no) [$5]="no" ; AC_MSG_RESULT(${[$5]}) ;;
                *) AC_MSG_RESULT([unknown])
                   AC_MSG_ERROR([bad value ${enableval} for --enable-$1]) ;;
	    ], [$7])
	    esac],
            [if test -z "${[$5]}" ; then
               [$5]="$6"
             fi
             AC_MSG_RESULT(${[$5]}) ; m4_if([$8], , , [$8])])
if test -z "${[$5]}" ; then
  [$5]="$6"
fi
])


## STP_ARG_WITH (NAME, HELP, VARIABLE, DEFAULT, [OPTION_TRUE], [OPTION_FALSE])
## ---------------------------------------------------------------------------
## NAME           Option name i.e. --with-foo or --enable-foo.
## HELP           Help string to display.
## VARIABLE       Variable to set with command-line results.
## DEFAULT        Default value of VARIABLE.
## OPTION_TRUE    case statement body if an option is supplied.
##                This replaces the default actions.
## OPTION_FALSE   shell commands to run if no option is supplied.
AC_DEFUN([STP_ARG_WITH],
[STP_ARG_WITH_DETAILED([$1], , [$2], , [$3], [$4], [$5], [$6])])

## STP_ARG_ENABLE (NAME, HELP, VARIABLE, DEFAULT, [OPTION_TRUE], [OPTION_FALSE])
## -----------------------------------------------------------------------------
## Identical to STP_ARG_WITH.
AC_DEFUN([STP_ARG_ENABLE],
[STP_ARG_ENABLE_DETAILED([$1], , [$2], , [$3], [$4], [$5], [$6])])




## --------------- ##
## 2. Conditionals ##
## --------------- ##


# STP_CONDITIONAL (OPTION)
# ------------------------
# Define automake conditional based on STP_ARG* results.  Until
# automake uses autoconf traces, this breaks automake
AC_DEFUN([STP_CONDITIONAL],
[AM_CONDITIONAL(BUILD_$1, test x${BUILD_$1} = xyes)])


## STP_ADD_COMPILER_ARG (ARG, COMPILER, VARIABLE)
## ---------------------------------------------------------------------------
## ARG            Compiler option
## COMPILER       Compiler name
## VARIABLE       Variable to add option to (default CFLAGS).
AC_DEFUN([STP_ADD_COMPILER_ARG],[
  AC_MSG_CHECKING(if m4_ifval([$2], [$2 ], [${CC} ])supports $1)
  stp_acOLDCFLAGS="${CFLAGS}"
  NCFLAGS="${m4_ifval([$3], [$3], [CFLAGS])} $1"
  CFLAGS="$NCFLAGS -Werror"
  AC_TRY_COMPILE(,,
      [ AC_MSG_RESULT(yes);
        stp_newCFLAGS="$NCFLAGS"],
      [ AC_MSG_RESULT(no);
	stp_newCFLAGS="$stp_acOLDCFLAGS"])
  CFLAGS="$stp_acOLDCFLAGS"
  m4_ifval([$3], [$3], [CFLAGS])="${stp_newCFLAGS}"
])

## STP_ADD_FIRST_COMPILER_ARG (ARGS, COMPILER, VARIABLE)
## ---------------------------------------------------------------------------
## ARGS           Compiler options
## COMPILER       Compiler name
## VARIABLE       Variable to add option to (default CFLAGS).
AC_DEFUN([STP_ADD_FIRST_COMPILER_ARG],[
  for stp_ac_arg in $1 ; do
    stp_ac_save_CFLAGS="${m4_ifval([$3], [$3], [CFLAGS])}"
    STP_ADD_COMPILER_ARG([${stp_ac_arg}], [$2], [$3])
    test "${stp_ac_save_CFLAGS}" != "${m4_ifval([$3], [$3], [CFLAGS])}" && break
  done
])

## STP_ADD_COMPILER_ARGS (ARGS, COMPILER, VARIABLE)
## ---------------------------------------------------------------------------
## ARGS           Compiler options
## COMPILER       Compiler name
## VARIABLE       Variable to add option to (default CFLAGS).
AC_DEFUN([STP_ADD_COMPILER_ARGS],[
  for stp_ac_arg in $1 ; do
    STP_ADD_COMPILER_ARG([${stp_ac_arg}], [$2], [$3])
  done
])

EOF

# shellcheck disable=SC2006,SC2154
test -f "$srcdir/configure.ac" && sed "s/XXXRELEASE_DATE=XXX/RELEASE_DATE=\"`date '+%d %b %Y'`\"/" "$srcdir/m4extra/stp_release.m4.in" > "$srcdir/m4/stp_release.m4"

# Make sure all of our auto* bits are up to date.
autoreconf -ivf

# shellcheck disable=SC2006
libtoolv=`libtool --version | head -1 | sed 's,.*[      ]\([0-9][0-9]*\.[0-9][0-9]*\(\.[0-9][0-9]*\)\?\).*[a-z]*\([   ]?.*\|\)$,\1,'`
if [ -n "$libtoolv" ] ; then
# shellcheck disable=SC2006
  libtool_major=`echo "$libtoolv" | awk -F. '{print $1}'`
# shellcheck disable=SC2006
  libtool_minor=`echo "$libtoolv" | awk -F. '{print $2}'`
# shellcheck disable=SC2006,SC2034
  libtool_point=`echo "$libtoolv" | awk -F. '{print $3}'`
  if [ "$libtool_major" -le 1 ] && [ "$libtool_minor" -lt 5 ] ; then
    libtool_err=1
  fi
else
  libtool_err=1
fi

if [ -z "`type -p glib-mkenums`" ] ; then
  echo
  echo "**Error**: You must have \`glib2-mkenums' installed to create a"
  echo "Gutenprint distribution.  This is usually distributed in the"
  echo "glib2-devel, glib2-dev, or similar package."
  DIE=1
fi

if [ -n "$libtool_err" ] ; then
  echo
  echo "**Warning**: You should have \`libtool' 1.5 or newer installed to"
  echo "create a Gutenprint distribution.  Earlier versions of libtool do"
  echo "not generate correct code for all platforms."
  echo "Get ftp://ftp.gnu.org/pub/gnu/libtool/libtool-1.5.tar.gz"
  echo "(or a newer version if it is available)"
  DIE=1
fi

(autoconf --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: You must have \`autoconf' installed to"
  echo "create a Gutenprint distribution."
  echo "Download the appropriate package for your distribution,"
  echo "or get the source tarball at ftp://ftp.gnu.org/pub/gnu/"
  DIE=1
}

test -f "$srcdir/ChangeLog" || echo > "$srcdir/ChangeLog"

(grep "^AM_PROG_LIBTOOL" "$srcdir/configure.ac" >/dev/null) && {
  (libtool --version) < /dev/null > /dev/null 2>&1 || {
    echo
    echo "**Error**: You must have \`libtool' installed to"
    echo "create a Gutenprint distribution."
    echo "Get ftp://ftp.gnu.org/pub/gnu/libtool/libtool-1.5.tar.gz"
    echo "(or a newer version if it is available)"
    DIE=1
  }
}

grep "^AM_GNU_GETTEXT" "$srcdir/configure.ac" >/dev/null && {
  grep "sed.*POTFILES" "$srcdir/configure.ac" >/dev/null || \
  (gettext --version) < /dev/null > /dev/null 2>&1 || {
    echo
    echo "**Error**: You must have \`gettext' installed to"
    echo "create a Gutenprint distribution."
    echo "Get ftp://ftp.gnu.org/pub/gnu/gettext/gettext-0.16.tar.gz"
    echo "(or a newer version if it is available)"
    DIE=1
  }
}

(pkg-config --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: You must have \`pkg-config' installed to"
  echo "create a Gutenprint distribution."
  echo "Download the appropriate package for your distribution,"
  echo "or get the source tarball at http://www.freedesktop.org/"
  DIE=1
}


#### MRS: The following now only generates a warning, since earlier
####      versions of gettext *do* work, they just don't create the
####      right uninstall code.

# shellcheck disable=SC2006
gettextv=`gettext --version | head -1 | awk '{print $NF}'`
gettext_err=1
if [ -n "$gettextv" ] ; then
# shellcheck disable=SC2006
  gettext_major=`echo "$gettextv" | awk -F. '{print $1}'`
# shellcheck disable=SC2006
  gettext_minor=`echo "$gettextv" | awk -F. '{print $2}'`
# shellcheck disable=SC2006,SC2034
  gettext_point=`echo "$gettextv" | awk -F. '{print $3}'`
  if [ "$gettext_major" -gt 0 ] || [ "$gettext_minor" -ge 16 ] ; then
    gettext_err=
  fi
fi
if [ -n "$gettext_err" ] ; then
  echo
  echo "**Warning**: You must have \`gettext' 0.16 or newer installed to"
  echo "create a Gutenprint distribution.  Earlier versions of gettext do"
  echo "not generate the correct 'make uninstall' code."
  echo "Get ftp://ftp.gnu.org/gnu/gettext/gettext-0.16.tar.gz"
  echo "(or a newer version if it is available)"
fi

(autopoint --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: You must have \`autopoint' installed to"
  echo "create a Gutenprint distribution."
  echo "Get ftp://ftp.gnu.org/pub/gnu/gettext/gettext-0.16.tar.gz"
  echo "(or a newer version if it is available)"
  DIE=1
  NO_AUTOMAKE=yes
}

(automake --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: You must have \`automake' installed to"
  echo "create a Gutenprint distribution."
  echo "Get ftp://ftp.gnu.org/pub/gnu/automake/automake-1.7.tar.gz"
  echo "(or a newer version if it is available)"
  DIE=1
  NO_AUTOMAKE=yes
}


# if no automake, don't bother testing for aclocal
test -n "$NO_AUTOMAKE" || (aclocal --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: Missing \`aclocal'.  The version of \`automake'"
  echo "installed doesn't appear recent enough."
  echo "Get ftp://ftp.gnu.org/pub/gnu/automake/automake-1.7.tar.gz"
  echo "(or a newer version if it is available)"
  DIE=1
}

# Check first for existence and then for proper version of Jade >= 1.2.1

jade_err=0

# Exists?
command -V jade >/dev/null 2>&1 || jade_err=1

# Proper rev?
test "$jade_err" -eq 0 && {
#  echo "Checking for proper revision of jade..."
# shellcheck disable=SC2006
  jade_version=`jade -v < /dev/null 2>&1 | grep -i "jade\"? version" | awk -F\" '{print $2}'`

  # jade:I: "openjade" version "1.3.2"
  if [ -z "$jade_version" ] ; then
# shellcheck disable=SC2006
    jade_version=`jade -v < /dev/null 2>&1 | grep -i 'jade"* version' | sed 's/"//g' | awk '{print $NF}'`
  fi
  if [ -z "$jade_version" ] ; then
    jade -v < /dev/null 2>&1
    jade_err=1
  else
# shellcheck disable=SC2006
    jade_version_major=`echo "$jade_version" | awk -F. '{print $1}'`
# shellcheck disable=SC2006
    jade_version_minor=`echo "$jade_version" | awk -F. '{print $2}'`
# shellcheck disable=SC2006
    jade_version_point=`echo "$jade_version" | awk -F. '{print $3}'`

    test "$jade_version_major" -ge 1 || jade_err=1

    test "$jade_version_minor" -lt 2 || {
	test "$jade_version_minor" -eq 2 -a "$jade_version_point" -lt 1
      } && jade_err=1
  fi
}
test "$jade_err" -gt 0 && {
  echo
  echo "***Warning***: You must have \"Jade\" version 1.2.1 or"
  echo "newer installed to build the Gutenprint user's guide."
  echo "Get ftp://ftp.jclark.com/pub/jade/jade-1.2.1.tar.gz"
  echo "(or a newer version if available)"
  echo
}

# Check for existence of dvips

command -V dvips >/dev/null 2>&1 || {
  echo
  echo "***Warning***: You must have \"dvips\" installed to"
  echo "build the Gutenprint user's guide."
  echo
}

# Check for existence of jadetex

command -V jadetex >/dev/null 2>&1 || {
  echo
  echo "***Warning***: You must have \"jadetex\" version 3.5 or"
  echo "newer installed to build the Gutenprint user's guide."
  echo "Get ftp://prdownloads.sourceforge.net/jadetex/jadetex-3.5.tar.gz"
  echo "(or a newer version if available)"
  echo
}

# Check for OpenJade >= 1.3

openjade_err=0

# Exists?
command -V openjade >/dev/null 2>&1 || openjade_err=1

# Proper rev?
test "$openjade_err" -eq 0 && {
#  echo "Checking for proper revision of openjade..."
# shellcheck disable=SC2006
  openjade_version=`openjade -v < /dev/null 2>&1 | sed 's/"//g' | grep -i "openjade version" | awk -F ' ' '{print $4}'`
  if [ -n "$openjade_version" ] ; then
# shellcheck disable=SC2006
    openjade_version_major=`echo "$openjade_version" | awk -F. '{print $1}'`
# shellcheck disable=SC2006
    openjade_version_minor=`echo "$openjade_version" | awk -F. '{print $2}'`
# shellcheck disable=SC2006
    openjade_version_minor=`echo "$openjade_version_minor" | awk -F- '{print $1}' | sed -e 's/\([0-9][0-9]*\).*/\1/'`

    if [ "$openjade_version_major" -lt 1 ] ; then
      openjade_error=1
    elif [ "$openjade_version_major" -eq 1 ] && [ "$openjade_version_minor" -lt 3 ] ; then
      openjade_error=1
    fi
  else
    openjade_err=1
  fi

  test "$openjade_err" -eq 1 && {
    echo " "
    echo "***Warning***: You must have \"OpenJade\" version 1.3 or"
    echo "newer installed to build the Gutenprint user's guide."
    echo "Get http://download.sourceforge.net/openjade/openjade-1.3.tar.gz"
    echo "(or a newer version if available)"
    echo " "
  }
}

command -V db2html >/dev/null 2>&1 || {
  echo " "
  echo "***Warning***: You must have \"db2html\" installed to"
  echo "build the Gutenprint user's guide."
  echo "This usually comes from packages named docbook-utils or docbook-toys."
  echo " "
}

command -V db2pdf >/dev/null 2>&1 || {
  echo " "
  echo "***Warning***: You must have \"db2pdf\" installed to"
  echo "build the Gutenprint user's guide."
  echo "This usually comes from packages named docbook-utils-pdf"
  echo "or docbook-toys."
  echo " "
}

# Check first for existence and then for proper version of sgmltools-lite >=3.0.2

sgmltools_err=0

# Exists?
command -V sgmltools >/dev/null 2>&1
test $? -ne 0 && sgmltools_err=1

# Proper rev?
test "$sgmltools_err" -eq 0 && {
#  echo "Checking for proper revision of sgmltools..."
# shellcheck disable=SC2006
  sgmltools_version=`sgmltools --version | awk '{print $3}'`

  if [ -n "$sgmltools_version" ] ; then
# shellcheck disable=SC2006
    sgmltools_version_major=`echo "$sgmltools_version" | awk -F. '{print $1}'`
# shellcheck disable=SC2006
    sgmltools_version_minor=`echo "$sgmltools_version" | awk -F. '{print $2}'`
# shellcheck disable=SC2006
    sgmltools_version_point=`echo "$sgmltools_version" | awk -F. '{print $3}'`

    test "$sgmltools_version_major" -ge 3 || sgmltools_err=1
    test "$sgmltools_version_minor" -gt 0 ||
      (test "$sgmltools_version_minor" -eq 0 -a "$sgmltools_version_point" -ge 2) ||
      sgmltools_err=1
  else
    sgmltools_err=1
  fi
}

test "$sgmltools_err" -eq 1 && {
  echo " "
  echo "***Warning***: You must have \"sgmltools-lite\" version 3.0.2"
  echo "or newer installed to build the Gutenprint user's guide."
  echo "Get https://sourceforge.net/projects/sgmltools-lite/files/latest/download"
  echo "(or a newer version if available)"
  echo " "
}

# Check for convert

command -V convert >/dev/null 2>&1
test $? -ne 0 && {
  echo " "
  echo "***Warning***: You must have \"convert\" installed to"
  echo "build the Gutenprint user's guide."
  echo "\"convert\" comes from the ImageMagick software package."
  echo "Go to http://imagemagick.sourceforge.net/http and get"
  echo "the file ImageMagick-5.3.1.tar.gz"
  echo "(or a newer version if available)"
  echo " "
}

# Check for docbook version 4
# Note workaround for Fedora installation
# Include path for Fedora Docbook. A bit circuitous, but Fedora appends
# a bunch of extra stuff to the name of the directory-- including the
# version of Fedora (eg -fc9).  We don't want to test for every version
# of Fedora and modern bourne shells won't expand the glob (*);
# therefore, we do a `find` first and then test to see if there are any
# results.

if test -d /usr/share/sgml/docbook ;  then
# shellcheck disable=SC2006
  fedora_docbook=`find /usr/share/sgml/docbook -type d -name 'sgml-dtd-4.*' -print`
fi

{
  test -d "/usr/share/sgml/docbook_4" || test -d "/usr/share/sgml/docbook/dtd/4.0" || test -d "/usr/share/sgml/docbook/dtd/4.1" || test -d "/usr/share/sgml/docbook_4.1" || test -n "$fedora_docbook"
} || {
  echo " "
  echo "***Warning***: You must have Docbook v4 installed to"
  echo "build the Gutenprint user's guide."
  echo " "
}

if test "$DIE" -eq 1; then
  exit 1
fi

if test -z "$*"; then
  echo "**Warning**: I am going to run \`configure' with no arguments."
  echo "If you wish to pass any to it, please specify them on the"
  # shellcheck disable=SC1117
  echo "\`$0\' command line."
  echo
fi

case $CC in
xlc )
  am_opt=--include-deps;;
esac

# We don't have subdirectories.  We don't want any untarred directories that
# contain configure.ac files to mess things up for us.
coin="$srcdir/configure.ac"
# shellcheck disable=SC2006
dr=`dirname "$coin"`
if test -f "$dr/NO-AUTO-GEN"; then
  echo skipping "$dr" -- flagged as no auto-gen
else
  echo processing "$dr"
# shellcheck disable=SC2006
  macrodirs=`sed -n -e 's,^dnl AM_ACLOCAL_INCLUDE(\(.*\)),\1,gp' < "$coin"`
  ( cd "$dr"
    aclocalinclude="$ACLOCAL_FLAGS"
    for k in $macrodirs; do
      if test -d "$k"; then
	aclocalinclude="$aclocalinclude -I $k"
      ##else
      ##  echo "**Warning**: No such directory \`$k'.  Ignored."
      fi
    done
    if grep "^AM_GNU_GETTEXT" configure.ac >/dev/null; then
      if grep "sed.*POTFILES" configure.ac >/dev/null; then
	: #do nothing -- we still have an old unmodified configure.ac
      else
	echo "Creating $dr/aclocal.m4 ..."
	rm -f aclocal.m4
	test -r aclocal.m4 || touch aclocal.m4
	# We've removed po/ChangeLog from the repository.  Version
	# 0.10.40 of gettext appends an entry to the ChangeLog every time
	# anyone runs autogen.sh.  Since developers do that a lot, and
	# then proceed to commit their entire sandbox, we wind up with
	# an ever-growing po/ChangeLog that generates conflicts on
	# a routine basis.  There's no good reason for this.
	echo 'This ChangeLog is redundant. Please see the main ChangeLog for i18n changes.' > po/ChangeLog
	echo >> po/ChangeLog
	echo 'This file is present only to keep po/Makefile.in.in happy.' >> po/ChangeLog
	echo "Running autopoint...  Ignore non-fatal messages."
	autopoint --force
	# shellcheck disable=SC2181
	if [ $? -ne 0 ] ; then
	    echo 'Autopoint failed!'
	    exit 1
	fi
	echo "Making $dr/aclocal.m4 writable ..."
	test -r "$dr/aclocal.m4" && chmod u+w "$dr/aclocal.m4"
      fi
    fi
    if grep "^AM_PROG_LIBTOOL" configure.ac >/dev/null; then
      echo "Running libtoolize..."
      libtoolize --force --copy
      # shellcheck disable=SC2181
      if [ $? -ne 0 ] ; then
	  echo 'Libtoolize failed!'
	  exit 1
      fi
    fi
    echo "Running aclocal $aclocalinclude ..."
    # shellcheck disable=SC2086
    aclocal $aclocalinclude
    # shellcheck disable=SC2181
    if [ $? -ne 0 ] ; then
	echo 'aclocal failed!'
	exit 1
    fi
    if grep "^AM_CONFIG_HEADER" configure.ac >/dev/null; then
      echo "Running autoheader..."
      autoheader
      # shellcheck disable=SC2181
      if [ $? -ne 0 ] ; then
	  echo 'autoheader failed!'
	  exit 1
      fi
    fi
    echo "Running automake --gnu $am_opt ..."
    automake --add-missing --force-missing --copy --gnu $am_opt
    # shellcheck disable=SC2181
    if [ $? -ne 0 ] ; then
	echo 'automake failed!'
	exit 1
    fi
    echo "Running autoconf ..."
    autoconf
    # shellcheck disable=SC2181
    if [ $? -ne 0 ] ; then
	echo 'autoconf failed!'
	exit 1
    fi
  ) || exit 1
fi

conf_flags="--enable-maintainer-mode" #--enable-iso-c

if test -z "$NOCONFIGURE"; then
  echo Running "$srcdir/configure" $conf_flags "$@" ...
  "$srcdir/configure" $conf_flags "$@" \
  && echo Now type \`make\' to compile "$PKG_NAME" || exit 1
else
  echo Skipping configure process.
fi
