#!/bin/sh

# Count processors in the system
#
# Copyright 2017 Robert Krawitz (rlk@alum.mit.edu)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Use explicit /bin/sh in the shebang line to allow this to work in
# a non-initialized workspace.

# User-specified value takes priority
if [ -n "$STP_PARALLEL" ] ; then
    echo $STP_PARALLEL
    exit 0
fi

# Linux
nproc=$(type -p nproc)
if [ -n "$nproc" ] ; then
    nproc
else
    echo 1
fi
