#!/bin/sh

set -e

sudo -E apt-get -y $(travis_apt_get_options) install \
  autoconf \
  autogen \
  automake \
  autopoint \
  bison \
  flex \
  gettext \
  libtool \
  pdfjam \
  time \
  zpaq

env |sort

set -x
STP_TEST_ROTOR=$1 \
  STP_TEST_ROTOR_CIRCUMFERENCE=$2 \
  STP_CONFIG_ARGS='--disable-nls --without-gimp2 --without-doc --without-cups --disable-libgutenprintui2 --disable-escputil' \
  TRAVIS_MODE=1 \
  ./scripts/build-release run_build_fresh run_checksums
