#!/bin/sh

set -e

env |sort
set -x
CC=$1 \
  STP_TEST_ROTOR=$2 \
  TRAVIS_MODE=1 \
  STP_CONFIG_ARGS='--without-doc --without-gimp2 --disable-libgutenprintui2 --disable-escputil' \
  ./scripts/build-release run_autogen run_build run_full run_valgrind
